/*Mehmet Duran Datetimepicker Uygulaması | 19.01.2009 */
var aylar = new Array();aylar[0]="Ocak";aylar[1]="Şubat";aylar[2]="Mart";aylar[3]="Nisan";aylar[4]="Mayıs";aylar[5]="Haziran";aylar[6]="Temmuz";aylar[7]="Ağustos";aylar[8]="Eylül";aylar[9]="Ekim";aylar[10]="Kasım";aylar[11]="Aralık";
var gunler_kisa = new Array();gunler_kisa[0]="Pzt";gunler_kisa[1]="Sal";gunler_kisa[2]="Çar";gunler_kisa[3]="Per";gunler_kisa[4]="Cum";gunler_kisa[5]="Cmt";gunler_kisa[6]="Pzr";
function ay_gun_sayisi_bul(month,year){var m = [31,28,31,30,31,30,31,31,30,31,30,31];if (month != 2) return m[month - 1];if (year%4 != 0) return m[1];if (year%100 == 0 && year%400 != 0) return m[1];return m[1] + 1;}
var tarih = new Date();var aktif_ay = tarih.getMonth();var aktif_yil = tarih.getFullYear();var bugun = tarih.getDate();
function takvim_olustur(){var takvim="";var ay_index = aktif_ay;tarih.setMonth(aktif_ay); tarih.setFullYear(aktif_yil);var gun = ay_gun_sayisi_bul(tarih.getMonth()+1,tarih.getFullYear());var baslangic = tarih.getDay();baslangic = (7 - ((bugun - baslangic) % 7) + 1) % 7;if (baslangic == 0) baslangic = 7;if(aktif_ay < 0) ay_index = (aktif_ay + 13);takvim += "<table><tr class=takvim_baslik><td onclick=geri() colspan=1><img src=geri.png /></td><td colspan=5>" + aylar[ay_index] + " - " + tarih.getFullYear() + "</td><td colspan=1 onclick=ileri()><img src=ileri.png /></td></tr>";takvim += "<tr><td class=gun_adi>"+gunler_kisa[0]+"</td><td class=gun_adi>"+gunler_kisa[1]+"</td><td class=gun_adi>"+gunler_kisa[2]+"</td><td class=gun_adi>"+gunler_kisa[3]+"</td><td class=gun_adi>"+gunler_kisa[4]+"</td><td class=gun_adi>"+gunler_kisa[5]+"</td><td class=gun_adi>"+gunler_kisa[6]+"</td></tr>";for(var i=1; i<gun+7; i=i+7){if (i < 7 ){takvim += "<tr class=gun_no>";for (var k = 1; k < baslangic; k++){takvim += "<td> </td>";}for (var m = 1; m <= 7 - baslangic + 1; m++){takvim += "<td onclick=sec("+m+","+(aktif_ay+1)+","+aktif_yil+")>" + m + "</td>";}takvim += "</tr>";}else if (i > 7){takvim += "<tr class=gun_no>"; var adet=0;for (var j = i - baslangic + 1; j < i + 8 - baslangic; j++){if (j > gun){ break; }takvim += "<td onclick=sec("+j+","+(aktif_ay+1)+","+aktif_yil+")>" + j + "</td>";adet +=1;}if(adet<7 && adet!=0)for(var t=0; t<7-adet; t++){takvim += "<td> </td>"};takvim += "</tr>";}}takvim += "</table>";return takvim;}
function ileri(){aktif_ay += 1; if(aktif_ay >= 12){ aktif_ay = aktif_ay%12; aktif_yil += 1;} $("#goster").html(takvim_olustur());}
function geri(){if(aktif_ay == 0){ aktif_ay=12; aktif_yil -= 1;} aktif_ay -= 1; $("#goster").html(takvim_olustur());}
/*Jquery Kullanımı. Jquery olmadan takvim_olustur() fonksiyonunu çağırarak herhangi bir elemente takvimimizi yükleyebiliriz.*/
function hazirla(){$("#takvim").focus(function(){$("#goster").html(takvim_olustur()).show("slow");});}
/*Takvimden gün seçtiğimizde text'e gelen değer. İstersek saat,dakika ve saniye bilgisini de ekleyebiliriz.*/
function sec(gun,ay,yil){$("#takvim").val(gun+"/"+ay+"/"+yil); $("#goster").hide("fast");}